version: "3"
services:
  app:
    container_name: express-mongoDB
    restart: always
    build: ./
    ports:
      - "80:3000"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongoDB
    image: mongo
    ports:
      - "27017:27017"
